from tkinter import * 
window=Tk()
window.geometry("400x300")
window.title("Math")

nameLabel=Label(text="Enter Number 1", bg="White")
nameLabel.pack()
nameEntry1=Entry()
nameEntry1.pack()
nameLabel=Label(text="Enter Number 2", bg="White")
nameLabel.pack()
nameEntry2=Entry()
nameEntry2.pack()

def add():
    num1=nameEntry1.get()
    num2=nameEntry2.get()
    num3=int(num1)+int(num2)
    textbox.insert(END,"Total = ")
    textbox.insert(END, num3)
    textbox.insert(END, "\n")
def sub():
    num1=nameEntry1.get()
    num2=nameEntry2.get()
    num3=int(num1)-int(num2)
    textbox.insert(END,"Differene = ")
    textbox.insert(END, num3)
    textbox.insert(END, "\n")
def mult():
    num1=nameEntry1.get()
    num2=nameEntry2.get()
    num3=int(num1)*int(num2)
    textbox.insert(END,"Product = ")
    textbox.insert(END, num3)
    textbox.insert(END, "\n")
def devi():
    num1=nameEntry1.get()
    num2=nameEntry2.get()
    num3=int(num1)/int(num2)
    textbox.insert(END,"Total = ")
    textbox.insert(END, num3)
    textbox.insert(END, "\n")

buttonAdd=Button(text="Add", bg="Red", command=add)
buttonAdd.pack()
buttonSub=Button(text="Sub", bg="Blue", command=sub)
buttonSub.pack()
buttonMult=Button(text="Mult", bg="Green", command=mult)
buttonMult.pack()
buttonDevi=Button(text="Devi", bg="Yellow", command=devi)
buttonDevi.pack()

textbox=Text(height=10)
textbox.pack()
window.mainloop()