import random
#print(random.randint(0,10))
#print(random.random())
#print(random.choice("Dhilan"))
#print(random.seed(4))
#print(random.random())
random.seed(5)
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))
random.seed(5)
print(random.random())
print(random.random())
print(random.random())
